apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cryptopredicts
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Grune4/CryptoPredicts.git
    targetRevision: main
    path: k8s
    directory:
      exclude: "secret-templates/*"
  destination:
    server: https://kubernetes.default.svc
    namespace: crypto-app
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true