apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  namespace: crypto-app
data:
  DB_HOST: "postgres"
  DB_PORT: "5432"
  DB_NAME: "crypto"
  SPRING_PROFILES_ACTIVE: "production"
  JAVA_OPTS: "-Xmx256m -Xms128m"
