apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: crypto-app
type: Opaque
stringData:
  POSTGRES_USER: crypto
  POSTGRES_PASSWORD: crypto-secure-password-change-in-prod
  POSTGRES_DB: crypto
