spring.application.name=Crypto
spring.datasource.url=jdbc:postgresql://das-crypto-db.postgres.database.azure.com:5432/crypto_db
spring.datasource.username=crypto_postgres
spring.datasource.password=Das2025@
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
cryptopanic.api.key=e875f1ba937f08540410dfb006fa7c86618bd54b